// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_mFcFwbawFuEV-K3SaOCEagyMmHfzkQ',
    appId: '1:1813498036:web:2ec7167a928c5039c2efe1',
    messagingSenderId: '1813498036',
    projectId: 'myfirstpfeprojecttest',
    authDomain: 'myfirstpfeprojecttest.firebaseapp.com',
    storageBucket: 'myfirstpfeprojecttest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpjSxgBorkC9T8Bgrm7lF66q5VSnFopI',
    appId: '1:1813498036:android:2421ce3ca0031ae7c2efe1',
    messagingSenderId: '1813498036',
    projectId: 'myfirstpfeprojecttest',
    storageBucket: 'myfirstpfeprojecttest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV-5mgpHzg7oyyHtE_tdATmnu_-TVBViM',
    appId: '1:1813498036:ios:57cf1216ffb71717c2efe1',
    messagingSenderId: '1813498036',
    projectId: 'myfirstpfeprojecttest',
    storageBucket: 'myfirstpfeprojecttest.appspot.com',
    iosBundleId: 'com.test.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV-5mgpHzg7oyyHtE_tdATmnu_-TVBViM',
    appId: '1:1813498036:ios:881d1d2e03264b45c2efe1',
    messagingSenderId: '1813498036',
    projectId: 'myfirstpfeprojecttest',
    storageBucket: 'myfirstpfeprojecttest.appspot.com',
    iosBundleId: 'com.test.testapp.RunnerTests',
  );
}
